version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app  
      - 'aluxion:/app/node_modules'
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    container_name: aluxion_db
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  aluxion:

